name: pull

on:
  pull_request:
    branches-ignore:
      - nightly
  push:
    branches:
      - main
      - release/*
      - landchecks/*
  workflow_dispatch:
  schedule:
    - cron: 29 8 * * *  # about 1:29am PDT

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

jobs:
  libtorch-linux-bionic-cuda12_1-py3_7-gcc9-build:
    name: libtorch-linux-bionic-cuda12.1-py3.7-gcc9
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: libtorch-linux-bionic-cuda12.1-py3.7-gcc9
      docker-image-name: pytorch-linux-bionic-cuda12.1-cudnn8-py3-gcc9
      build-generates-artifacts: false
      runner: linux.4xlarge
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 1 },
        ]}
