# upload alerts every 15 minutes

name: Upload Alerts to AWS/Rockset

on:
  pull_request:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  upload_alerts:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python Packages
        run: |
          pip3 install rockset==1.0.3
          pip3 install boto3==1.19.12

      - name: Create alerts
        run: |
          output=$(tools/alerts/create_alerts.py)
          echo "output is the following"
          echo $output
          ehco "end of output"
          echo "::set-output name=script_output::$output"
        id: alert_creation_step
      - name: Upload alerts
        uses: pytorch/test-infra/.github/actions/upload-alerts@main
        with:
          alerts: ${{ steps.alert_creation_step.outputs.script_output }}
          organization: "pytorch"
          repo: "pytorch"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true